### ISSUE TITLE
Suggest support http:// and https:// in ConsoleLink

### ISSUE THREAD

**Issue by pichuang** [openshift/console-operator#397]
I found the console link don't support `http://`. Is there have any concern on this?

For example:
```yaml
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: haproxy-stats
spec:
  href: 'http://lb.ocp4.internal:38084/stats'
  location: HelpMenu
  text: HAProxy Stats for Red Hat OpenShift Cluster
```
