### ISSUE TITLE
How to change default console port  (443) in OpenShift 4

### ISSUE THREAD

**Issue by ogre0403** [openshift/console-operator#468]
Hi, 

We just migrate from OpenShift 3.11 to  4.3 recently, the console port is changed from 8443 to standard HTTPS 443 port. 

For security consideration, we usually don't expose such control plan console in standard port. 
Is it possible to change console port to other value ? 

thank.

**Comment by jhadvig** [comment]
Hey @ogre0403,
so based on the [docs](https://docs.openshift.com/container-platform/3.11/install_config/certificate_customization.html#configuring-custom-certificates) the port number of console Service was `443` back then as well. Not sure whats is the issue then.

Checked descirption for `console` Service in the 3.11 cluster:
```
oc get service -n openshift-console console -o yaml
apiVersion: v1
kind: Service
metadata:
  name: console
  namespace: openshift-console
   ...
spec:
  clusterIP: 172.30.230.211
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: openshift-console
    component: ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

In the 4.x version the console is managed by the console-operator, if you are not familiar with operators concept please check these [docs](https://docs.openshift.com/container-platform/4.5/operators/olm-what-operators-are.html).
Console operator is managing the openshift web console and currently there is no way how to customize the port number.
