### ISSUE TITLE
Update `oauth.yaml` to the appropriate annotations once ready

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/console-operator#47]
Possibly will match something like this:

```yaml
apiVersion: oauth.openshift.io/v1
kind: OAuthClient
metadata:
  name: openshift-console
  annotations:
    # match the route name
    # alpha.mo.will.let.us.define.route: console
    # alpha.mo.will.let.us.define.namespace: openshift-console
grantMethod: auto
respondWithChallenges: false
```

if @enj makes it work

/assign @enj
