### ISSUE TITLE
Bug: affinity rule created in console deployment for single-replica infrastructure

### ISSUE THREAD

**Issue by michael-topchiev** [openshift/console-operator#656]
Console operator erroneously creates console deployment with an affinity rule when running in a cluster with HA control plane (ControlPlaneTopology=="HighlyAvailable"/"External") and non-HA infrastructure plane (InfrastructureTopology=="SingleReplica").

To reproduce the issue, create an OCP cluster with 3 control plane nodes and 1 worker node. Console deployment will have non-empty affinity clause, even though the number of console replicas is 1:
```
kind: Deployment
apiVersion: apps/v1
...
  name: console
  ...
spec:
  replicas: 1
  ...
  template:
    ...
    spec:
      ...
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - ui
              topologyKey: kubernetes.io/hostname
...
```
This issue causes console deployment updates to stall because new console replica will not start on the same single worker node due to the anti-affinity rule.
